// Bump APP_VERSION on every release (v1.0, v1.1, v1.2 …) and add a line to RELEASES.
export const APP_VERSION = "1.62";

/** One change in a release, shown in the "Update available" banner: what changed, where to see it, and why. */
export type Change = { what: string; where: string; why: string };
export const RELEASE_AUTHOR = "Vipin";

export const RELEASES: { version: string; date: string; notes: string; changes?: Change[] }[] = [
  { version: "1.62", date: "2026-09-28", notes: "Scores shown as percentages: Rank, ICP Match, Opportunity, Coupa Fit and Persona fit (e.g. 91%).",
    changes: [
      { what: "Rank, ICP Match, Opportunity, Coupa Fit and Persona fit show a % sign (e.g. Rank 91%, ICP Match 100%); each score's parts read '12 of 20 pts'; hovering Rank shows how it is built", where: "Pipeline, Accounts, account page scores, Stakeholders, Define ICP (minimum ICP Match), Learn Me, Master Book (Persona Fit %)", why: "The scores are percentages of the maximum points, so the % makes them read correctly" },
    ] },
  { version: "1.61", date: "2026-09-28", notes: "Team: a Standard User can be given several regions (tick boxes). PIN saving reports the exact reason if it fails. Costs note: Vercel Pro covers Deep research.",
    changes: [
      { what: "Region(s) is a tick-box list: one Standard User can cover several regions (e.g. KSA and Qatar); only Super Admins can set it", where: "Setup → Settings → Team (invite and Change access)", why: "Some colleagues handle more than one market" },
      { what: "If the paid-actions PIN can't be saved, the message under the field now gives the exact reason from the server or database", where: "Setup → Settings → Paid-actions PIN", why: "Saving the PIN was failing without a clear reason" },
      { what: "Costs note corrected: your Vercel Pro plan already allows the longer function time Deep research needs", where: "Setup → Settings → Costs & usage", why: "It wrongly suggested the free tier and a possible upgrade" },
    ] },
  { version: "1.60", date: "2026-09-28", notes: "Paid-actions PIN: saving shows 'Saving…' and the result right under the field; eye button to show the PIN; tick box after 'Ask Super Admins too'. Eye button on the sign-in password too.",
    changes: [
      { what: "Saving the PIN shows 'Saving…', then the result right under the field and as a notice at the top centre; if it fails, the reason is shown and your typed PIN is kept", where: "Setup → Settings → 2 · Paid refresh → Paid-actions PIN", why: "Saving looked like it never finished — the result appeared far away at the top of the section" },
      { what: "Eye button to show or hide what you type", where: "Paid-actions PIN field, the PIN window on paid actions, and the sign-in password", why: "So you can check what you're saving or entering" },
      { what: "Layout: PIN field → 'Ask Super Admins too' with its tick box after the sentence → Save PIN", where: "Setup → Settings → Paid-actions PIN", why: "Reads in the order you decide" },
    ] },
  { version: "1.59", date: "2026-09-28", notes: "Team invite form on one row — Work email · Name · Role · Region · How · Invite — with light-filled fields.",
    changes: [
      { what: "Invite form in one aligned row: Work email, Name, Role, Region, How, Invite (Role now sits before Region instead of above it)", where: "Setup → Settings → Team", why: "Role was stacked above Region, which looked out of order" },
      { what: "Light colour fills per field: blue for email and name, purple for Role, green for Region, amber for How; the same colours in 'Change access'", where: "Setup → Settings → Team", why: "Easier to scan and see which choice is which" },
    ] },
  { version: "1.58", date: "2026-09-28", notes: "Paid-actions PIN: anything that costs Anthropic API money asks for a PIN in the app first; set by a Super Admin, checked on the server.",
    changes: [
      { what: "Paid-actions PIN: Research more, Draft pitch plan, Research Queue, Research again and the paid Refresh ask for a PIN in an in-app window before anything is spent; a wrong PIN spends nothing, and 5 wrong tries lock it for 15 minutes", where: "Any paid button (amber Cost impact note)", why: "So colleagues can use the app without accidentally spending your API credit" },
      { what: "Set or change the PIN, and choose whether Super Admins are asked too", where: "Setup → Settings → 2 · Paid refresh → Paid-actions PIN", why: "You decide who can spend; until a PIN is set, only Super Admins can run paid actions" },
    ] },
  { version: "1.57", date: "2026-09-28", notes: "Define ICP now drives the scores: focus platforms, ERP of interest and buying triggers change Opportunity and Coupa Fit (and so the Pipeline); buyer personas rank Stakeholders, the Contact List and guide research. Settings: Refresh and API spend & balance merged into one Paid refresh section, credit first.",
    changes: [
      { what: "Buying triggers and ERP of interest add to the Opportunity score (up to 20 and 10 points) when an account shows them; focus platforms add to Coupa Fit (up to 20). Hover a score to see 'Your buying triggers', 'Your ERP of interest' or 'Your platform focus'", where: "Accounts → Pipeline (rank), account page scores", why: "What you choose in Define ICP should visibly change which accounts come first" },
      { what: "Persona fit (0–100) for every contact — department, seniority and priority role against your buyer personas; Stakeholders are ranked by it, with a Persona fit filter", where: "Stakeholders tab", why: "Your buyer personas now decide who appears first" },
      { what: "Master Book Contact List adds Persona Fit and Persona Match; within each company the best-fitting people come first", where: "Master Book → Contact List", why: "The outreach list follows your personas" },
      { what: "Research Queue pre-selects contact roles from your personas, and every paid research brief includes your priority roles, seniority, contact limit, focus platforms, ERP and triggers", where: "Data → Research Queue", why: "Research looks for the people and signals you defined" },
      { what: "Refresh and Anthropic API spend & balance are one section, '2 · Paid refresh': A · Your API credit (balance, spend, carry-over) first, then B · Plan a refresh", where: "Setup → Settings", why: "They are two halves of the same thing — see your credit, then decide what to spend" },
    ] },
  { version: "1.56", date: "2026-09-28", notes: "In-app confirmation windows replace the browser pop-ups (save ICP, reset, research, refresh, engine token), and a notice at the top centre confirms each save.",
    changes: [
      { what: "In-app confirmation window in the centre of the screen, in the app's colours, listing what will happen, with clear buttons (e.g. 'Save & apply', 'Start refresh'); paid actions show the cost in an amber box; risky ones are red", where: "Define ICP save and reset, Research more, Refresh, engine token", why: "The browser's grey pop-up was easy to miss and didn't look part of the app" },
      { what: "A notice at the top centre of the screen confirms the result (e.g. 'ICP saved as v2 and applied — 3 accounts changed status') or explains what to fix", where: "Setup → Define ICP (Save & apply, Preview impact)", why: "The result used to appear at the bottom of a long page" },
    ] },
  { version: "1.55", date: "2026-09-28", notes: "Define ICP: a save bar appears at the bottom of the screen as soon as you change anything, and the page warns you before leaving with unsaved changes.",
    changes: [
      { what: "Save bar: as soon as you change a setting, a bar stays at the bottom of the screen — 'Not saved yet' — with Discard, Preview impact and Save & apply", where: "Setup → Define ICP (bottom of the screen)", why: "Selections are a draft until saved, and the only Save button was at the top of the page" },
      { what: "Leaving the page with unsaved changes asks you to confirm first", where: "Setup → Define ICP", why: "So a draft is never lost by accident" },
    ] },
  { version: "1.54", date: "2026-09-28", notes: "Roles and regions: Super Admin (all regions, consolidated view, team, engine, every ICP) and Standard User (one region: its data and its ICP only). Set in Setup → Settings → Team; enforced by the app and the database.",
    changes: [
      { what: "Roles: Super Admin sees every region together and one by one, and manages the team, engine and all ICPs; Standard User is assigned a region and the whole app (dashboard, accounts, Pipeline, research, daily run, Master Book) works only on that region by its ICP", where: "Setup → Settings → Team (Role and Region when inviting; 'Change' on each person)", why: "A Europe or USA colleague should control only their market, without access to other regions" },
      { what: "Define ICP follows the role: a Standard User sees and edits only their region's rules; a Super Admin edits every region. This replaces the single-owner lock", where: "Setup → Define ICP", why: "Each region owns its ICP" },
      { what: "Region tiles show only your regions (Super Admins also get 'All regions', the consolidated view); Europe, USA and Bahrain are now tiles too", where: "Country bar under the main tabs", why: "Standard users should only see their own market" },
      { what: "Database protection: region rules are also enforced inside the database, and shared settings can be written only by Super Admins (one-time update to run in Supabase)", where: "Behind the scenes", why: "So nobody can go around the app to see or change another region" },
      { what: "Learn Me explains roles and regions", where: "Setup → Learn Me → Get to know me", why: "Anyone reading it should know who can see and change what" },
    ] },
  { version: "1.53", date: "2026-09-28", notes: "Readability fixes: white text on count badges; the Refresh plan is labelled as a preview (nothing spent until you click); Console balance shown as a coloured dollar field with a filled Save balance button.",
    changes: [
      { what: "Count badges (e.g. '1 users') use white text on a darker green", where: "Every heading with a count, e.g. Setup → Settings → Team", why: "Black text on green was hard to read" },
      { what: "The Refresh plan line is labelled 'Preview — nothing spent yet' and explains that $20 is only the starting value in the Budget box, with the per-item estimates it uses", where: "Setup → Settings → Discovery & refresh engine → 2 · Refresh", why: "It looked like a real balance of $20" },
      { what: "Console balance is a green dollar field ($ prefix, bold amount) and Save balance is a filled button", where: "Setup → Settings → Anthropic API spend & balance", why: "Makes the money value and the action stand out" },
    ] },
  { version: "1.52", date: "2026-09-28", notes: "Owner-only lock on Define ICP: once you make yourself the ICP owner, only owners can save changes; teammates can view and preview.",
    changes: [
      { what: "Owner-only lock: click 'Make me the ICP owner' once; after that only the owner(s) can change and save the ICP. Teammates see the page read-only and can still use Preview impact", where: "Setup → Define ICP → owner strip above the region tiles", why: "The ICP drives every search, verification and Pipeline rank, so one accountable owner prevents accidental changes" },
      { what: "Manage owners: add co-owners or hand over ownership (at least one owner is always kept)", where: "Setup → Define ICP → Manage owners", why: "So ownership can be shared or passed on without a code change" },
    ] },
  { version: "1.51", date: "2026-09-28", notes: "Define ICP shows money in USD as $250M / $3.5B; you can type 250M or 3.5B. Local currency is used only for conversion.",
    changes: [
      { what: "Revenue fields show USD amounts the way you read them: $250M, and $3.5B from $1,000M upward; type 250, 250M or 3.5B and the field confirms the value", where: "Setup → Define ICP → Company size, Evidence & verification", why: "A bare '250' with 'USD M' beside it was easy to misread" },
      { what: "Local currency is labelled 'for conversion only', with an example (e.g. AED 3,673M = $1B); every amount shown is in USD", where: "Setup → Define ICP → Region & daily run", why: "One display currency avoids mistakes; local figures are only converted" },
    ] },
  { version: "1.50", date: "2026-09-28", notes: "Define ICP: region status offers only the moves that make sense — Active: 'Pause the daily run'; Paused: 'Make … Active' (and 'Mark as next phase' only with no accounts); Next phase: 'Make … Active' or 'Pause'.",
    changes: [
      { what: "Clearer status buttons: an Active region shows one button, 'Pause the daily run', with what happens; 'Next phase' is offered only for regions with no accounts yet", where: "Setup → Define ICP → 1 · Region & daily run", why: "'Change to Next phase' made no sense for a live market like UAE and caused confusion" },
      { what: "Every status button says its outcome, and a note reminds you it takes effect when you click Save & apply", where: "Setup → Define ICP → 1 · Region & daily run", why: "So nobody wonders what a click will do" },
    ] },
  { version: "1.49", date: "2026-09-28", notes: "Define ICP: settings 2–9 are open only for an Active region. Paused and Next-phase regions show them greyed out and locked, with 'Make … Active' or 'Edit rules without starting the daily run'.",
    changes: [
      { what: "Settings 2–9 (size, type, industries, never add, evidence, pipeline, personas, notes) can be edited only when the selected region is Active; for Paused and Next-phase regions they are greyed out and locked", where: "Setup → Define ICP", why: "Editing a region that isn't running was confusing" },
      { what: "A banner on locked regions explains why and offers two choices: 'Make … Active' (unlocks and starts the daily run) or 'Edit rules without starting the daily run' (to prepare Europe or USA in advance; 'Lock again' to undo)", where: "Setup → Define ICP → Paused or Next-phase region", why: "Keeps the safe default while still letting you prepare a new market before it goes live" },
      { what: "Region & daily run spans the full width at the top of the page", where: "Setup → Define ICP → 1 · Region & daily run", why: "It now comes first, before the settings it unlocks" },
    ] },
  { version: "1.48", date: "2026-09-28", notes: "Define ICP is region first: Step 1 choose a region, Step 2 set its rules. Section 1 shows only that region's current status (e.g. UAE is Active) with a small 'Change to' option.",
    changes: [
      { what: "Clear order: 'Step 1 · Choose a region' above the region tiles and 'Step 2 · Set the rules for …' above the settings", where: "Setup → Define ICP", why: "It wasn't clear whether to pick a status or a region first" },
      { what: "Region & daily run shows only the selected region's status (UAE is Active, KSA is Paused, Europe is Next phase) with what it means; the other statuses are small 'Change to' buttons", where: "Setup → Define ICP → 1 · Region & daily run", why: "Showing all three statuses at once looked like a choice to make before choosing a country" },
    ] },
  { version: "1.47", date: "2026-09-28", notes: "Define ICP region tiles: full text visible, light status colours, all nine regions in one row on wide screens.",
    changes: [
      { what: "Region tiles show everything: region name with its status dot, the status, and the number of accounts; tiles grow to fit instead of cutting text off", where: "Setup → Define ICP → region tiles", why: "The status and account count were cut off" },
      { what: "Light colour per status: green for Active, amber for Paused, grey for Next phase; the selected region has a teal outline", where: "Setup → Define ICP → region tiles", why: "See at a glance which markets are running" },
      { what: "All nine regions fit in one row on wide screens", where: "Setup → Define ICP", why: "USA dropped onto a second row on its own" },
    ] },
  { version: "1.46", date: "2026-09-28", notes: "Define ICP: steady layout (nothing shifts when you select an option) and a clear explanation of Region & daily run — what each choice means and its outcome.",
    changes: [
      { what: "Region & daily run explained: three choice cards (Active, Paused, Next phase), each saying what it means and what will happen; the daily numbers show what they produce (e.g. about 150 new accounts a month) and grey out when the region isn't Active", where: "Setup → Define ICP → 1 · Region & daily run", why: "So you know exactly what to pick and what the agent will do after you save" },
      { what: "Steady layout: selecting an option no longer changes text weight or widths, region tabs have a fixed size, and messages (unsaved changes, things to fix) no longer push the page around", where: "Setup → Define ICP", why: "The menu jumped when you selected an option" },
      { what: "Switching a region to Active pre-fills a starting daily run (find 5, verify 25) that you can change", where: "Setup → Define ICP → 1 · Region & daily run", why: "An active region with no daily numbers would do nothing" },
    ] },
  { version: "1.45", date: "2026-09-28", notes: "Company logos in the app's tables, the account page and the Master Book (Accounts, Contact List), sized to the row; Define ICP layout fixed.",
    changes: [
      { what: "Company logo column: each company's website icon in a small square beside its name; neutral initials when a company has no icon. Row heights are unchanged", where: "Accounts, Pipeline, dashboard priority list, drill-down lists and the account page", why: "Recognise companies at a glance and make the lists easier to scan" },
      { what: "Logos in the Master Book: a 16px logo inside each row of Accounts and Contact List (rows stay the same height; formulas and the dashboard adjusted for the new column)", where: "Master Book → Accounts, Contact List", why: "The same at-a-glance recognition in the file you share" },
      { what: "Define ICP page layout fixed: the settings cards now fill the page width instead of being pushed to the right, and dropdowns stay inside their cards", where: "Setup → Define ICP", why: "An old style name clashed with the new page and squeezed it to one side" },
    ] },
  { version: "1.44", date: "2026-09-28", notes: "Define ICP: a full ICP editor per region (UAE, KSA, Qatar, Kuwait, Oman, Bahrain, Egypt; Europe and USA as next phase). Every rule the agent follows is set here and applied everywhere: ICP status, verification, the 6am run, in-app research, the Pipeline and the left panel. Preview impact before saving; change history.",
    changes: [
      { what: "Define ICP editor: set company size (revenue and staff range, revenue measure for banks and insurers), listing, ownership, entity level, industries, exclusions, evidence rules, re-check interval, Pipeline weights and entry threshold, focus platforms, ERP and triggers, buyer personas and the daily run — separately for each region", where: "Setup → Define ICP", why: "Your ICP is the foundation of every search and verification; now you control it directly, with no hidden rules" },
      { what: "One source of truth: ICP status, the 6am run, in-app research, the Pipeline and the left panel all read Define ICP; saving recalculates every account's status at once", where: "Accounts, Pipeline, bell summaries after the next 6am run", why: "No misalignment between what you define and what the agent does" },
      { what: "Preview impact before saving (how many accounts change status in each region, and why) and a change history showing who changed what and when", where: "Setup → Define ICP → Preview impact / Change history", why: "See the effect of a rule change before it happens, and keep an audit trail" },
      { what: "Regions: UAE active; KSA, Qatar, Kuwait, Oman, Bahrain and Egypt ready (paused until you switch them on); Europe and USA listed as the next phase, each with its own rules and currency", where: "Setup → Define ICP → region tabs", why: "Each market has its own ICP and parameters" },
      { what: "The 6am run now reads your ICP first and works only in active regions, with each region's daily numbers", where: "Bell summary after the next run", why: "Switching a region on, or changing the daily numbers, takes effect the next morning without any code change" },
      { what: "Learn Me intro updated to explain that everything follows Define ICP", where: "Setup → Learn Me → Get to know me", why: "The introduction always describes how the agent actually works" },
    ] },
  { version: "1.43", date: "2026-09-28", notes: "Master Book redesigned (Nunito 12, clear colour tags, dashboard cards with a sheet guide, HubSpot columns in Accounts); bigger tab fonts; Admin renamed Setup with Define ICP, Settings and Learn Me; the update banner now lists what changed, where and why.",
    changes: [
      { what: "Master Book redesigned: Nunito 12 throughout, navy-and-white layout, soft row banding, colour tags for ICP status, S2P signals and HubSpot actions; prints landscape on one page width", where: "Master Book button (top bar) → every sheet", why: "Easier to read, scan and present to your team" },
      { what: "Executive Dashboard rebuilt as cards (Verified, Likely, Needs check, in HubSpot, people to contact…) with a clickable guide to every sheet; ICP line corrected (a stock listing is not required)", where: "Master Book → Executive Dashboard", why: "The first sheet should answer 'where do we stand?' at a glance and show where to go next" },
      { what: "Accounts sheet shows In HubSpot, HubSpot Stage and HubSpot Owner; HubSpot columns have a teal header everywhere", where: "Master Book → Accounts, Contact List", why: "See straight away which accounts SCP already works, without switching to HubSpot" },
      { what: "Larger main-tab and sub-tab text", where: "Top navigation", why: "Tabs now have two rows, so they no longer need to be squeezed" },
      { what: "Admin renamed Setup, with Define ICP · Settings · Learn Me (Guide renamed Learn Me)", where: "Top navigation → Setup", why: "Groups everything that sets up how the agent works; Define ICP becomes the home of your ICP rules" },
      { what: "This banner lists every change with where to see it and why", where: "Update banner (top of the page)", why: "So you know exactly what to look at after each upgrade" },
    ] },
  { version: "1.42", date: "2026-09-28", notes: "Duplicates merged into one record per company (ASGC, Al Faraa, Khansaheb): original record kept, empty fields filled, stronger revenue evidence kept, other names and websites stored as aliases so the engine never re-adds them. Guide 'Get to know me': the whole agent explained in framed steps (find, verify, one record per company, HubSpot, smart moves). Today's bell message corrected." },
  { version: "1.41", date: "2026-09-28", notes: "Daily engine: stronger duplicate check before adding discovered companies (spelling variants, acronyms, domains, group vs subsidiary); the run reads the existing company list first and replaces any duplicate so 5 genuinely new companies are added. Clearer bell summary. Guide explains the check." },
  { version: "1.40", date: "2026-09-27", notes: "HubSpot sync (read-only, kept inside this app): each account shows whether it is in SCP's HubSpot, its stage, owner and deals. Master Book Contact List adds Deals, Latest Deal, Contact in HubSpot and a HubSpot Import Action (skip / add contact / new company) to avoid duplicate imports; new HubSpot Deals sheet. Guide: new plain-language introduction; the title now gently pulses (heart removed)." },
  { version: "1.39", date: "2026-09-27", notes: "Guide Master Book: HubSpot connection explained — what the agent reads from HubSpot, what is used today and where it shows." },
  { version: "1.38", date: "2026-09-27", notes: "Master Book Contact List: Existing SCP Customer (company exists in HubSpot), Company Stage and Company Owner from HubSpot." },
  { version: "1.37", date: "2026-09-27", notes: "Master Book: new Contact List sheet (one row per person; company, website, full name, job title, phone, official email, location, LinkedIn, Existing SCP Customer). Guide explains how the Master Book is prepared, every sheet and how to study it." },
  { version: "1.36", date: "2026-09-27", notes: "Spend estimates re-based on published industry benchmarks (McKinsey, AHA, CBRE, CFMA, APQC and others) with a confidence label and source for every sector; shown in the Guide and in each estimate." },
  { version: "1.35", date: "2026-09-27", notes: "Guide: Pipeline explained in tables — weights and why, entry rules, and worked examples showing how 50% / 30% / 20% combine into the rank." },
  { version: "1.34", date: "2026-09-27", notes: "Guide: the 'Get to know me' title now has a live heartbeat (pulsing heart, ECG line and glow in a lub-dub rhythm)." },
  { version: "1.33", date: "2026-09-27", notes: "Main tabs without sub-tabs (Dashboard, Stakeholders) no longer repeat their name in the sub-tab bar; the bar keeps its height so nothing jumps." },
  { version: "1.32", date: "2026-09-27", notes: "Guide: 'What the app can\'t do (yet) — and why' now explains LinkedIn signals, real spend data and Phase 2 (how it would add, refresh and update data) in detail." },
  { version: "1.31", date: "2026-09-27", notes: "Guide: Costs and Record dates explained in tables with worked examples." },
  { version: "1.30", date: "2026-09-27", notes: "Faster, steadier navigation: the top bar is built once and stays put across pages (no jumping), an instant loading placeholder shows while a page loads, and the full data load is cached for 60 seconds (refreshed after every update). Fixed: Guide 'Get to know me' now shows when selected." },
  { version: "1.29", date: "2026-09-27", notes: "Guide shows one section at a time: click a tile in the contents to open it (selected tile highlighted, remembered in the link)." },
  { version: "1.28", date: "2026-09-27", notes: "Colourful Guide: each section has its own accent colour, filled table headers and striped rows; 'Get to know me' is a highlighted panel; live checks show as filled badges; the contents list is a coloured panel of clickable tiles. Light mode: selected main tab and selected sub-tab are now clearly different." },
  { version: "1.27", date: "2026-09-27", notes: "Guide opens with 'Get to know me — I'm your Account CoPilot AI Agent (Autonomous)': the Daily 6AM Run Process (find 5 new ICP companies, verify 25) and Logic Followed in Account CoPilot, checked live against the app's data. Duplicate accounts merged." },
  { version: "1.26", date: "2026-09-27", notes: "Light and dark mode (sun/moon switch in the top bar; follows your computer until you choose), with every text colour checked for readability (4.5:1 contrast) in both. Bell moved next to the version button." },
  { version: "1.25", date: "2026-09-27", notes: "Re-check cycle: any non-Verified company (including Not ICP) is re-verified 180 days after its last check, so growing companies move up to ICP — Verified." },
  { version: "1.24", date: "2026-09-27", notes: "Sub-tabs line up under their main tab (the last sub-tab ends beneath it); Master Book, bell and profile sit on the same row as the main tabs." },
  { version: "1.23", date: "2026-09-27", notes: "Bell checks for new engine runs every minute and when you return to the tab. New ICP rule: companies whose estimates are below $100M with 1,000 staff or fewer become Not ICP (estimate) instead of staying in Needs check; reopened automatically if an official figure appears." },
  { version: "1.22", date: "2026-09-26", notes: "Scheduled session access: a limited engine token (Settings) lets the 6am Claude session read queues, submit results, add companies and post notifications without any database key. ICP status rules shared by scripts and the app." },
  { version: "1.21", date: "2026-09-26", notes: "Notification bell in the top bar: each scheduled 6am engine run posts a summary (companies verified, new companies added); also listed in Settings → Scheduled run history." },
  { version: "1.20", date: "2026-09-26", notes: "Navigation option B (active tab joined to a coloured sub-tab bar). Settings → Discovery & refresh engine: queue no-cost searches (30 / 50 / max, by region) for scheduled Claude sessions; budgeted Refresh with carry-over and a clear explanation before you click; measured API spend and an estimated balance. Sobha Constructions merged into Sobha Realty." },
  { version: "1.19", date: "2026-09-26", notes: "Simpler left panel: changes apply instantly; Save for team / Discard changes appear only when you have changes; Restore default ICP is a small link with confirmation. Trust tiles show their definitions; Guide explains why big companies can be Likely." },
  { version: "1.18", date: "2026-09-26", notes: "Navigation grouped into five main tabs (Dashboard, Accounts, Stakeholders, Data, Admin) with sub-tabs on a line beneath the top bar, so every tab fits." },
  { version: "1.17", date: "2026-09-26", notes: "Simpler sources: Origin (one per company, adds up to the total), Contributors (inside your workbook), Trust (companies by ICP status; contacts as one record per person: Confirmed by 2+ sources / Single source / Conflicting) and Evidence. Stakeholders one row per person with a source-by-source comparison on the contact card. Left panel: Refresh, Save and Reset each show their own result; edits are a draft until applied." },
  { version: "1.16", date: "2026-09-26", notes: "Upgrade button flashes while the new version loads, then a steady 'Updated to vX ✓' bar confirms it." },
  { version: "1.15", date: "2026-09-26", notes: "Pipeline scoring fix: full revenue points only for official revenue figures (estimates get a third), so the Pipeline shows genuinely verified targets (UAE: 432 → 78)." },
  { version: "1.14", date: "2026-09-26", notes: "Guide tab: every feature, the scoring point system, spend-estimate formulas and how the engine works. Research more button in the left panel (finds and optionally profiles new ICP companies for the selected country; cost note and confirmation). ICP status set automatically after in-app research." },
  { version: "1.13", date: "2026-09-26", notes: "Sources tab moved next to Stakeholders: colour source tiles (Source | Region, companies profiled, click to view) for channels and evidence types, a source catalogue (what, provides, how collected, reliability, cost) and a Source group filter; duplicate source rows removed." },
  { version: "1.12", date: "2026-09-26", notes: "Account Discovery Criteria panel (left): company and contact criteria saved for the team; ICP Match, Opportunity and Coupa Fit scores with breakdowns; ranked Pipeline tab; AI intelligence in account briefs (why selected, spend estimates, recommended actions); 224 Seamless discovery accounts; user-confirmed Coupa customers." },
  { version: "1.11", date: "2026-09-25", notes: "Footer: Designed and created by Vipin." },
  { version: "1.10", date: "2026-09-25", notes: "Country tiles under the nav filter the dashboard and every tab; record dates (added, updated, status since) in Accounts, briefs and Excel; cost-impact notes on actions that use the Anthropic API; all nav tabs fit on screen; revenue checks keep their notes on recompute." },
  { version: "1.9", date: "2026-09-25", notes: "Filters stay on one row; row count moved below the filters." },
  { version: "1.8", date: "2026-09-25", notes: "Clickable dashboard tiles open a drill-down of the records behind each number; contact cards from Stakeholders and account briefs." },
  { version: "1.7", date: "2026-09-25", notes: "Profile menu (name, email, joined from, log out), invite colleagues, Costs & usage guide in Settings, header keeps Download on the first row." },
  { version: "1.6", date: "2026-09-25", notes: "Colour-filled filters that light up when active; Clear filters button." },
  { version: "1.5", date: "2026-09-25", notes: "One ICP scale (revenue ≥ $250M, 100+ staff; listing not required): Verified, Likely, Needs check, Unknown, Not ICP. Best-available revenue with its source." },
  { version: "1.4", date: "2026-09-25", notes: "ICP status combines your revenue figure with Seamless; revenue conflicts flagged; reason shown on hover and in the account brief; ICP legend on Accounts." },
  { version: "1.3", date: "2026-09-25", notes: "Revenue shown as $6.04B / $600M in the app and Excel." },
  { version: "1.2", date: "2026-09-25", notes: "Navy + teal theme, logo, gradient app name, colour-edged KPI tiles and colourful charts, page hero panels, upgrade banner, instant tab switching, counts next to table titles, role family grouped by department, reference-sheet annotation rows moved to Conflicts, Seamless verification of your target list." },
  { version: "1.1", date: "2026-09-25", notes: "Your target lists imported: 158 more accounts, all 665 stakeholder contacts, ICP status and list tags, Your profiling panel, Target List (Reference) Excel tab." },
  { version: "1.0", date: "2026-09-25", notes: "First release: dashboard, accounts, stakeholders, S2P signals, ERP & apps, conflicts, sources, research queue, pitch planner, Excel export, version badge." },
];
