// Bump APP_VERSION on every release (v1.0, v1.1, v1.2 …) and add a line to RELEASES.
export const APP_VERSION = "1.22";

export const RELEASES: { version: string; date: string; notes: string }[] = [
  { version: "1.22", date: "2026-09-26", notes: "Scheduled session access: a limited engine token (Settings) lets the 6am Claude session read queues, submit results, add companies and post notifications without any database key. ICP status rules shared by scripts and the app." },
  { version: "1.21", date: "2026-09-26", notes: "Notification bell in the top bar: each scheduled 6am engine run posts a summary (companies verified, new companies added); also listed in Settings → Scheduled run history." },
  { version: "1.20", date: "2026-09-26", notes: "Navigation option B (active tab joined to a coloured sub-tab bar). Settings → Discovery & refresh engine: queue no-cost searches (30 / 50 / max, by region) for scheduled Claude sessions; budgeted Refresh with carry-over and a clear explanation before you click; measured API spend and an estimated balance. Sobha Constructions merged into Sobha Realty." },
  { version: "1.19", date: "2026-09-26", notes: "Simpler left panel: changes apply instantly; Save for team / Discard changes appear only when you have changes; Restore default ICP is a small link with confirmation. Trust tiles show their definitions; Guide explains why big companies can be Likely." },
  { version: "1.18", date: "2026-09-26", notes: "Navigation grouped into five main tabs (Dashboard, Accounts, Stakeholders, Data, Admin) with sub-tabs on a line beneath the top bar, so every tab fits." },
  { version: "1.17", date: "2026-09-26", notes: "Simpler sources: Origin (one per company, adds up to the total), Contributors (inside your workbook), Trust (companies by ICP status; contacts as one record per person: Confirmed by 2+ sources / Single source / Conflicting) and Evidence. Stakeholders one row per person with a source-by-source comparison on the contact card. Left panel: Refresh, Save and Reset each show their own result; edits are a draft until applied." },
  { version: "1.16", date: "2026-09-26", notes: "Upgrade button flashes while the new version loads, then a steady 'Updated to vX ✓' bar confirms it." },
  { version: "1.15", date: "2026-09-26", notes: "Pipeline scoring fix: full revenue points only for official revenue figures (estimates get a third), so the Pipeline shows genuinely verified targets (UAE: 432 → 78)." },
  { version: "1.14", date: "2026-09-26", notes: "Guide tab: every feature, the scoring point system, spend-estimate formulas and how the engine works. Research more button in the left panel (finds and optionally profiles new ICP companies for the selected country; cost note and confirmation). ICP status set automatically after in-app research." },
  { version: "1.13", date: "2026-09-26", notes: "Sources tab moved next to Stakeholders: colour source tiles (Source | Region, companies profiled, click to view) for channels and evidence types, a source catalogue (what, provides, how collected, reliability, cost) and a Source group filter; duplicate source rows removed." },
  { version: "1.12", date: "2026-09-26", notes: "Account Discovery Criteria panel (left): company and contact criteria saved for the team; ICP Match, Opportunity and Coupa Fit scores with breakdowns; ranked Pipeline tab; AI intelligence in account briefs (why selected, spend estimates, recommended actions); 224 Seamless discovery accounts; user-confirmed Coupa customers." },
  { version: "1.11", date: "2026-09-25", notes: "Footer: Designed and created by Vipin." },
  { version: "1.10", date: "2026-09-25", notes: "Country tiles under the nav filter the dashboard and every tab; record dates (added, updated, status since) in Accounts, briefs and Excel; cost-impact notes on actions that use the Anthropic API; all nav tabs fit on screen; revenue checks keep their notes on recompute." },
  { version: "1.9", date: "2026-09-25", notes: "Filters stay on one row; row count moved below the filters." },
  { version: "1.8", date: "2026-09-25", notes: "Clickable dashboard tiles open a drill-down of the records behind each number; contact cards from Stakeholders and account briefs." },
  { version: "1.7", date: "2026-09-25", notes: "Profile menu (name, email, joined from, log out), invite colleagues, Costs & usage guide in Settings, header keeps Download on the first row." },
  { version: "1.6", date: "2026-09-25", notes: "Colour-filled filters that light up when active; Clear filters button." },
  { version: "1.5", date: "2026-09-25", notes: "One ICP scale (revenue ≥ $250M, 100+ staff; listing not required): Verified, Likely, Needs check, Unknown, Not ICP. Best-available revenue with its source." },
  { version: "1.4", date: "2026-09-25", notes: "ICP status combines your revenue figure with Seamless; revenue conflicts flagged; reason shown on hover and in the account brief; ICP legend on Accounts." },
  { version: "1.3", date: "2026-09-25", notes: "Revenue shown as $6.04B / $600M in the app and Excel." },
  { version: "1.2", date: "2026-09-25", notes: "Navy + teal theme, logo, gradient app name, colour-edged KPI tiles and colourful charts, page hero panels, upgrade banner, instant tab switching, counts next to table titles, role family grouped by department, reference-sheet annotation rows moved to Conflicts, Seamless verification of your target list." },
  { version: "1.1", date: "2026-09-25", notes: "Your target lists imported: 158 more accounts, all 665 stakeholder contacts, ICP status and list tags, Your profiling panel, Target List (Reference) Excel tab." },
  { version: "1.0", date: "2026-09-25", notes: "First release: dashboard, accounts, stakeholders, S2P signals, ERP & apps, conflicts, sources, research queue, pitch planner, Excel export, version badge." },
];
